spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/lingjing_baas?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:127.0.0.1}
    password: ${REDIS_PASSWORD:password}
    port: ${REDIS_PORT:6379}

  zipkin:
    base-url: ${ZIPKIN:http://172.168.3.64:9411}
  sleuth:
    sampler:
      #采样取值介于 0到1之间，1则表示全部收集
      probability: 1

dna:
  account:
    adminAccount: ${ADMIN_ACCOUNT:0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
    walletDir: ${WALLET_DIR:temp/wallets/}
  node:
    restUrl: ${NODE_URL:http://127.0.0.1:8545}

pdfs:
  cli:
    host: ${PDFS_HOST:172.168.3.13}
    port: ${PDFS_PORT:22}
    username: ${PDFS_USER:ubuntu}
    password: ${PDFS_PASS:Onchain@2019}
    baseDir: ${PDFS_BASE_FOLDER:/home/ubuntu/pdfs/pdfs-cli}
    uploadFolder: ${PDFS_UPLOAD:temp/upload}
  rpc:
    uploadUrl: ${PDFS_UPLOAD_URL:http://172.168.3.13:21337/api/v1/uploadFile}
    downloadUrl: ${PDFS_DOWNLOAD_URL:http://172.168.3.13:21337/api/v1/downloadbyhash}

jwt:
  secret:
    code: ${JWT_CODE:01234567}

cloud:
  cos:
    secretId: AKID1pNhmajVeX8UbWPaswjESWQ5Tt7AkusZ
    secretKey: 2jFbhX8Weo8D8yc8RTEsGRRfKjsmOYR2
    regionName: ap-shanghai
    bucketName: onchain-bill-dev-1302609605
    httpProtocol: ${COS_HTTP:http}

  sms:
    endpoint: sms.tencentcloudapi.com
    secretId: AKIDqXzB6l2t5wqCJc7nKa09UBbAV22KxSDe
    secretKey: cS10XIGyhMlxxqufAO0OijTFtTmwvleE
    appId: 1400471113
    registerTempId: 857603
    loginTempId: 857605
    authTempId: 857608
    sign: 分布科技
    test: ${SMS_TEST:true}
