spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://121.4.146.202:3306/lingjing_baas?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:121.4.146.202}
    password: ${REDIS_PASSWORD:password}
    port: ${REDIS_PORT:6379}

  zipkin:
    base-url: ${ZIPKIN:http://121.4.146.202:9411}
  sleuth:
    sampler:
      #采样取值介于 0到1之间，1则表示全部收集
      probability: 1

chain:
  maas:
    adminAccount: ${ADMIN_ACCOUNT:4b0c9b9d685db17ac9f295cb12f9d7d2369f5bf524b3ce52ce424031cafda1ae}
    rpcUrl: ${NODE_URL:https://maas-test-node.onchain.com}
    configAddress: ${CONFIG_CONTRACT:0xD62B67170A6bb645f1c59601FbC6766940ee12e5}
    explorerUrl: ${EXP_URL:https://test-explorer.lingjing-eco.com.cn}

jwt:
  secret:
    code: ${JWT_CODE:01234567}

cloud:
  cos:
    secretId: AKID1pNhmajVeX8UbWPaswjESWQ5Tt7AkusZ
    secretKey: 2jFbhX8Weo8D8yc8RTEsGRRfKjsmOYR2
    regionName: ap-shanghai
    bucketName: onchain-bill-dev-1302609605
    httpProtocol: ${COS_HTTP:http}

  sms:
    endpoint: sms.tencentcloudapi.com
    secretId: AKIDqXzB6l2t5wqCJc7nKa09UBbAV22KxSDe
    secretKey: cS10XIGyhMlxxqufAO0OijTFtTmwvleE
    appId: 1400471113
    registerTempId: 857603
    loginTempId: 857605
    verifyTempId: 1551091
    sign: 分布科技
    test: ${SMS_TEST:true}

privatekey:
  encode:
    key: ${ENCODE_KEY:aGVsbG9vbmNoYWluYnJvdA==}
    offset: ${ENCODE_OFFSET:1234567890123456}

sj:
  appId: APLAW7zZwGnsd1YsTQ2fa2TLQeinkPgjG7
  appSecret: ASGW85yC3dFE9vx32uX5rDs8Zy9jM7u5IK
  chainId: Metanu91c2bkedqs
  assetRegisterUrl: https://chainbridge.chinadep.com/api/v1/assets/register
  getTokenUrl: https://chainbridge.chinadep.com/platform/api/platform/token
  refreshTokenUrl: https://chainbridge.chinadep.com/platform/api/platform/refreshToken

wechat:
  appId: wx88fb37e63492da21
  appSecret: 2fd4359fbe09d863b5c56edfaadfd38b

api:
  token: ${API_TOKEN:LJTLQeinkPgjG75IK}

sj2:
  appId: AP7sNFmQCDb8ZKbR7tDbpUf2MnLFcKBjwV
  appKey: ASLvmAQAdxt8xizoQfvRoDUvfHgC4d7KX2
  assetUpdateUrl: https://uat-dat.chinadep.com/api/market/out/v1/assets
  assetCustomerUrl: https://uat-dat.chinadep.com/api/market/out/v1/customerAssets
  assetRightsUrl: https://uat-dat.chinadep.com/api/market/out/v1/assetsRight

