spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://124.221.156.86:3306/dna2_baas?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true}
    username: ${MYSQL_USERNAME:dna}
    password: ${MYSQL_PASSWORD:Xsz6Cd5Djka1IEmW}

  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:172.168.3.12}
    password: ${REDIS_PASSWORD:password}
    port: ${REDIS_PORT:6379}

  zipkin:
    base-url: ${ZIPKIN:http://172.168.3.12:9411}
  sleuth:
    sampler:
      #采样取值介于 0到1之间，1则表示全部收集
      probability: 1

chain:
  maas:
    adminAccount: ${ADMIN_ACCOUNT:4b0c9b9d685db17ac9f295cb12f9d7d2369f5bf524b3ce52ce424031cafda1ae}
    rpcUrl: ${NODE_URL:https://maas-test-node.onchain.com}
    configAddress: 0xD62B67170A6bb645f1c59601FbC6766940ee12e5

jwt:
  secret:
    code: ${JWT_CODE:01234567}

cloud:
  cos:
    secretId: AKIDczQ3ycrMTJsBKD6CKQXNwGg16uT1ovxj
    secretKey: n1zg15IFuOcZFeJZZHm1zg50dz4vyvde
    regionName: ap-shanghai
    bucketName: onchain-bill-test-1302609605
    httpProtocol: ${COS_HTTP:https}

  sms:
    endpoint: sms.tencentcloudapi.com
    secretId: AKIDqXzB6l2t5wqCJc7nKa09UBbAV22KxSDe
    secretKey: cS10XIGyhMlxxqufAO0OijTFtTmwvleE
    appId: 1400471113
    registerTempId: 857603
    loginTempId: 857605
    authTempId: 857608
    sign: 分布科技
    test: ${SMS_TEST:false}

privatekey:
  encode:
    key: ${ENCODE_KEY:aGVsbG9vbmNoYWluYnJvdA==}
    offset: ${ENCODE_OFFSET:1234567890123456}