server:
  port: ${PORT:7701}

spring:
  application:
    name: baas-gateway
  profiles:
    active: ${ENV:dev}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
