spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://121.4.146.202:3306/dna2_explorer?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:121.4.146.202}
    password: ${REDIS_PASSWORD:password}
    port: ${REDIS_PORT:6379}

  zipkin:
    base-url: ${ZIPKIN:http://121.4.146.202:9411}
  sleuth:
    sampler:
      #采样取值介于 0到1之间，1则表示全部收集
      probability: 1

dna:
  node:
    restUrl: ${NODE_URL:https://test-node.lingjing-eco.com.cn}
    syncNodeUrl: ${SYNC_NODE_URL:http://43.142.51.74:8545}

cloud:
  captcha:
    secretId: AKIDYxA9tQksmRs41B7oHVVGm47vVrQBuRmv
    secretKey: zlKhsrdCZjgRzKSOL6dyHMDpCMHxOaYH
    userIp: 116.227.210.109
    captchaAppId: 194416799
    appSecretKey: rJjiPgUHdsIVLic2c3nFj4hP6
    endPoint: captcha.tencentcloudapi.com
